// Code generated by coz. DO NOT EDIT.
/**
 * scopes
 * @module scopes
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const retry_ = require('./retry')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.retry = _d(retry_)

module.exports = {
  retry: _d(retry_),
}
