// Code generated by coz. DO NOT EDIT.
/**
 * DB hook creators
 * @module hook
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const UserHook_ = require('./UserHook')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.UserHook = _d(UserHook_)

module.exports = Object.freeze({
  UserHook: _d(UserHook_),
})
