// Code generated by coz. DO NOT EDIT.
/**
 * Module mappings
 * @module mappings
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const StoryMapping_ = require('./StoryMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.StoryMapping = _d(StoryMapping_)

module.exports = Object.freeze({
  StoryMapping: _d(StoryMapping_),
})
