// Code generated by coz. DO NOT EDIT.
/**
 * Story mapping
 * @namespace StoryMapping
 */
'use strict'

const st = require('../stories')

module.exports = Object.freeze({
  'signInOut': st.SignInOutStory,
})
