// Code generated by coz. DO NOT EDIT.
/**
 * View components
 * @module views
 */
'use strict'

import AboutPrivacyPolicyView from './about/AboutPrivacyPolicyView'
import AboutTermsOfUseView from './about/AboutTermsOfUseView'
import AdminTopView from './admin/AdminTopView'
import AdminUserManageView from './admin/AdminUserManageView'
import ErrorForbiddenView from './error/ErrorForbiddenView'
import ErrorNotfoundView from './error/ErrorNotfoundView'
import HomeView from './HomeView'
import MypageView from './mypage/MypageView'
import PasswordChangeView from './password/PasswordChangeView'
import ProfileEditView from './profile/ProfileEditView'
import QuitView from './quit/QuitView'
import RecoverResetView from './recover/RecoverResetView'
import RecoverSendView from './recover/RecoverSendView'
import SignAskView from './sign/SignAskView'
import SignInView from './sign/SignInView'
import SignOutView from './sign/SignOutView'
import SignUpView from './sign/SignUpView'
import VerifyConfirmView from './verify/VerifyConfirmView'

export {
 AboutPrivacyPolicyView,
 AboutTermsOfUseView,
 AdminTopView,
 AdminUserManageView,
 ErrorForbiddenView,
 ErrorNotfoundView,
 HomeView,
 MypageView,
 PasswordChangeView,
 ProfileEditView,
 QuitView,
 RecoverResetView,
 RecoverSendView,
 SignAskView,
 SignInView,
 SignOutView,
 SignUpView,
 VerifyConfirmView,
}
