// Code generated by coz. DO NOT EDIT.
/**
 * Story concerns
 * @module concerns
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const accountOperative_ = require('./accountOperative')
const compose_ = require('./compose')
const passwordOperative_ = require('./passwordOperative')
const profileOperative_ = require('./profileOperative')
const signOperative_ = require('./signOperative')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.accountOperative = _d(accountOperative_)
exports.compose = _d(compose_)
exports.passwordOperative = _d(passwordOperative_)
exports.profileOperative = _d(profileOperative_)
exports.signOperative = _d(signOperative_)

module.exports = {
  accountOperative: _d(accountOperative_),
  compose: _d(compose_),
  passwordOperative: _d(passwordOperative_),
  profileOperative: _d(profileOperative_),
  signOperative: _d(signOperative_),
}
