// Code generated by coz. DO NOT EDIT.
/**
 * Story concerns
 * @module concerns
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get accountOperative () { return _d(require('./accountOperative')) },
  get compose () { return _d(require('./compose')) },
  get signOperative () { return _d(require('./signOperative')) },
}
