// Code generated by coz. DO NOT EDIT.
/**
 * Project configurations
 * @module conf
 */
'use strict'

import GlobalKeys from './GlobalKeys'
import HistoryTypes from './HistoryTypes'
import Icons from './Icons'
import Lifetimes from './Lifetimes'
import LocaleNames from './LocaleNames'
import RoleCodes from './RoleCodes'
import Styles from './Styles'
import UI from './UI'
import Urls from './Urls'
import locales from './locales'

export {
  GlobalKeys,
  HistoryTypes,
  Icons,
  Lifetimes,
  LocaleNames,
  RoleCodes,
  Styles,
  UI,
  Urls,
  locales,
}

