// Code generated by coz. DO NOT EDIT.
/**
 * scopes
 * @module scopes
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const reset_ = require('./reset')
const send_ = require('./send')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.reset = _d(reset_)
exports.send = _d(send_)

module.exports = {
  reset: _d(reset_),
  send: _d(send_),
}
