// Code generated by coz. DO NOT EDIT.
/**
 * Fragment components
 * @module stateless
 */
'use strict'

import UserCard from './cards/UserCard'
import UserImage from './images/UserImage'

export {
  UserCard,
  UserImage,
}

