// Code generated by coz. DO NOT EDIT.
/**
 * Stateless components
 * @module stateless
 */
'use strict'

import UserCard from './cards/UserCard'
import UserImage from './images/UserImage'
import FooterLessStyle from './styles/FooterLessStyle'
import HeaderLessStyle from './styles/HeaderLessStyle'

export {
 UserCard,
 UserImage,
 FooterLessStyle,
 HeaderLessStyle,
}
