// Code generated by coz. DO NOT EDIT.
/**
 * HOC Wrappers
 * @module wrappers
 */
'use strict'

import ofUser from './ofUser'
import onlySigned from './onlySigned'
import withMoment from './withMoment'
import withRole from './withRole'

export {
 ofUser,
 onlySigned,
 withMoment,
 withRole,
}
