// Code generated by coz. DO NOT EDIT.
/**
 * Dialogs Component
 */
'use strict'

import React from 'react'
import { stateful } from 'the-component-mixins'
import {
  AdminUserCreateDialog,
  AdminUserDestroyDialog,
  AdminUserPasswordDialog,
  AdminUserRoleDialog,
  ConnectionRetryDialog,
} from '../stateful'

class Dialogs extends React.Component {
  render () {
    return (
      <>
        <AdminUserCreateDialog/>
        <AdminUserDestroyDialog/>
        <AdminUserPasswordDialog/>
        <AdminUserRoleDialog/>
        <ConnectionRetryDialog/>
      </>
    )
  }
}

export default Dialogs
