// Code generated by coz. DO NOT EDIT.
/**
 * Endpoint routes
 * @module routes
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const aliasRoute_ = require('./aliasRoute')
const uploadRoute_ = require('./uploadRoute')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.aliasRoute = _d(aliasRoute_)
exports.uploadRoute = _d(uploadRoute_)

module.exports = {
  aliasRoute: _d(aliasRoute_),
  uploadRoute: _d(uploadRoute_),
}
