// Code generated by coz. DO NOT EDIT.
/**
 * Scopes
 * @module scopes
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m


const abstractCall_ = _d(require('./abstract/call.json'))
const abstractDetail_ = _d(require('./abstract/detail.json'))
const abstractFilter_ = _d(require('./abstract/filter.json'))
const abstractHash_ = _d(require('./abstract/hash.json'))
const abstractInput_ = _d(require('./abstract/input.json'))
const abstractList_ = _d(require('./abstract/list.json'))
const abstractProcess_ = _d(require('./abstract/process.json'))
const account_ = _d(require('./account.json'))
const adminUserCheck_ = _d(require('./admin/user/check.json'))
const adminUserCreate_ = _d(require('./admin/user/create.json'))
const adminUserDestroy_ = _d(require('./admin/user/destroy.json'))
const adminUserFilter_ = _d(require('./admin/user/filter.json'))
const adminUserList_ = _d(require('./admin/user/list.json'))
const adminUserPassword_ = _d(require('./admin/user/password.json'))
const adminUserRole_ = _d(require('./admin/user/role.json'))
const app_ = _d(require('./app.json'))
const connectionRetry_ = _d(require('./connection/retry.json'))
const passwordChange_ = _d(require('./password/change.json'))
const profileEdit_ = _d(require('./profile/edit.json'))
const quit_ = _d(require('./quit.json'))
const recoverReset_ = _d(require('./recover/reset.json'))
const recoverSend_ = _d(require('./recover/send.json'))
const signAsk_ = _d(require('./sign/ask.json'))
const signIn_ = _d(require('./sign/in.json'))
const signOut_ = _d(require('./sign/out.json'))
const signUp_ = _d(require('./sign/up.json'))
const toast_ = _d(require('./toast.json'))
const verifyConfirm_ = _d(require('./verify/confirm.json'))
const verifyNeed_ = _d(require('./verify/need.json'))
const verifySend_ = _d(require('./verify/send.json'))

exports.abstract = {}
exports.abstract.call = abstractCall_
exports.abstract.detail = abstractDetail_
exports.abstract.filter = abstractFilter_
exports.abstract.hash = abstractHash_
exports.abstract.input = abstractInput_
exports.abstract.list = abstractList_
exports.abstract.process = abstractProcess_
exports.account = account_
exports.admin = {}
exports.admin.user = {}
exports.admin.user.check = adminUserCheck_
exports.admin.user.create = adminUserCreate_
exports.admin.user.destroy = adminUserDestroy_
exports.admin.user.filter = adminUserFilter_
exports.admin.user.list = adminUserList_
exports.admin.user.password = adminUserPassword_
exports.admin.user.role = adminUserRole_
exports.app = app_
exports.connection = {}
exports.connection.retry = connectionRetry_
exports.password = {}
exports.password.change = passwordChange_
exports.profile = {}
exports.profile.edit = profileEdit_
exports.quit = quit_
exports.recover = {}
exports.recover.reset = recoverReset_
exports.recover.send = recoverSend_
exports.sign = {}
exports.sign.ask = signAsk_
exports.sign.in = signIn_
exports.sign.out = signOut_
exports.sign.up = signUp_
exports.toast = toast_
exports.verify = {}
exports.verify.confirm = verifyConfirm_
exports.verify.need = verifyNeed_
exports.verify.send = verifySend_
