// Code generated by coz. DO NOT EDIT.
/**
 * Server middlewares
 * @module middlewares
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const tokenMW_ = require('./tokenMW')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.tokenMW = _d(tokenMW_)

module.exports = Object.freeze({
  tokenMW: _d(tokenMW_),
})
