// Code generated by coz. DO NOT EDIT.
/**
 * Constant variables
 * @module constants
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get E2EConfig () { return _d(require('./E2EConfig')) },
  get GlobalExpressions () { return _d(require('./GlobalExpressions')) },
}
