// Code generated by coz. DO NOT EDIT.
/**
 * E2E Stories
 * @module stories
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get signInStory () { return _d(require('./signInStory')) },
}
