// Code generated by coz. DO NOT EDIT.
/**
 * E2E Stories
 * @module stories
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get PasswordChangeStory () { return _d(require('./00.PasswordChangeStory')) },
  get SignInOutStory () { return _d(require('./00.SignInOutStory')) },
  get Story () { return _d(require('./Story')) },
  get concerns () { return _d(require('./concerns')) },
}
